/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAdminProductsRouteImport } from './routes/_admin/admin.products'
import { Route as AdminAdminOrdersRouteImport } from './routes/_admin/admin.orders'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin.dashboard'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminProductsRoute = AdminAdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminOrdersRoute = AdminAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/products': typeof AdminAdminProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/products': typeof AdminAdminProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/product/$id': typeof ProductIdRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/orders': typeof AdminAdminOrdersRoute
  '/_admin/admin/products': typeof AdminAdminProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/login'
    | '/product/$id'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/product/$id'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/admin/login'
    | '/product/$id'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/orders'
    | '/_admin/admin/products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/products': {
      id: '/_admin/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/orders': {
      id: '/_admin/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminOrdersRoute: typeof AdminAdminOrdersRoute
  AdminAdminProductsRoute: typeof AdminAdminProductsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminOrdersRoute: AdminAdminOrdersRoute,
  AdminAdminProductsRoute: AdminAdminProductsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
